name: Publicar site no GitHub Pages
on:
  push:
    branches:
      - main # Ou a branch principal do seu repo fonte

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código-fonte
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Instalar dependências
        run: pip install mkdocs-material

      - name: Construir o site
        run: mkdocs build
        # 👇 ADICIONE ESTA LINHA PARA ENTRAR NA PASTA PRIMEIRO
        working-directory: meu-site-musical

      - name: Publicar no pcliquet.github.io
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: pcliquet/pcliquet.github.io
          publish_branch: main
          # 👇 ALTERE ESTA LINHA PARA APONTAR PARA A PASTA CORRETA
          publish_dir: ./meu-site-musical/
          force_orphan: true